2020-12-06 15:29:49,046 INFO log.py[ln:15] 正在登录 1284753334@qq.com ...
2020-12-06 15:32:10,841 INFO log.py[ln:15] 正在登录 1284753334@qq.com ...
2020-12-06 15:39:32,803 INFO log.py[ln:15] 正在登录 1284753334@qq.com ...
2020-12-06 15:39:47,212 INFO log.py[ln:15] 正在登录 1284753334@qq.com ...
2020-12-06 15:40:05,560 INFO log.py[ln:15] 正在登录 1284753334@qq.com ...
2020-12-06 15:49:19,815 INFO log.py[ln:15] 正在登录 1284753334@qq.com ...
2020-12-06 15:50:19,317 INFO log.py[ln:15] 正在登录 1284753334@qq.com ...
2020-12-06 15:50:20,618 ERROR log.py[ln:23] 账号 1284753334@qq.com  邮件发送失败.
2020-12-06 15:50:20,670 ERROR log.py[ln:23] Traceback (most recent call last):
  File "E:/codeworkpace/project/TTADSpider/sent_mail/class attach_mail.py", line 63, in sent
    print(3/0)
ZeroDivisionError: division by zero

